default_language_version:
    python: python3.7

repos:
#-   repo: https://github.com/asottile/seed-isort-config
#    rev: v1.9.2
#    hooks:
#    - id: seed-isort-config
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    - id: isort
# -   repo: https://github.com/ambv/black
#     rev: stable
#     hooks:
#     - id: black
#       language_version: python3.7
#       entry: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
    # - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
      exclude: |
          (?x)(
              ^node_modules/|
              ^static/|
              ^media/
          )
    - id: flake8
    - id: trailing-whitespace
      files: (^|/)a/.+\.(py|html|sh|css|js)$
      args: [--no-markdown-linebreak-ext]
      exclude: |
          (?x)(
              ^node_modules/|
              ^static/|
              ^media/
          )
    - id: check-yaml
      files: 'local.yml, production.yml'
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
    -   id: forbid-crlf
        exclude: |
            (?x)(
                ^node_modules/|
                ^static/|
                ^media/
            )
    -   id: remove-crlf
        exclude: |
            (?x)(
                ^node_modules/|
                ^static/|
                ^media/
            )
    -   id: forbid-tabs
        exclude: |
            (?x)(
                ^node_modules/|
                ^static/|
                ^media/
            )
    -   id: remove-tabs
        exclude: |
            (?x)(
                ^node_modules/|
                ^static/|
                ^media/
            )
        args: [ --whitespaces-count, "4" ]  # defaults to: 4
    # -   id: insert-license
    #     files: \.py$
    #     args:
    #     - --license-filepath
    #     - src/license_header.txt          # defaults to: LICENSE.txt
    #     - --comment-style
    #     - #                              # defaults to: #
-   repo: git://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.0
    hooks:
    -   id: rst-linter
-   repo: local
    hooks:
    -   id: forbid-en-dashes
        name: Detect the EXTREMELY confusing unicode character U+2013
        language: system
        entry: perl -ne 'print if $m = /\xe2\x80\x93/; $t ||= $m; END{{exit $t}}'
        files: ''
        exclude: |
            (?x)(
                ^node_modules/|
                ^static/|
                ^media/
            )
    -   id: remove-en-dashes
        name: Remove the EXTREMELY confusing unicode character U+2013
        language: system
        entry: perl -pi* -e 's/\xe2\x80\x93/-/g && ($t = 1) && print STDERR $_; END{{exit
            $t}}'
        files: ''
        exclude: |
            (?x)(
                ^node_modules/|
                ^static/|
                ^media/
            )
#    -   id: css-forbid-px
#        name: In CSS files, use rem or % over px
#        language: pygrep
#        entry: px
#        files: \.(css|scss|sass)$
    -   id: ot-sanitize-fonts
        name: Calling ot-sanitise on otf/ttf/woff/woff2 font files
        language: system
        entry: sh -c 'type ot-sanitise >/dev/null && for font in "$@"; do echo "$font"; ot-sanitise "$font"; done || echo "WARNING Command ot-sanitise not found - skipping check"'
        files: \.(otf|ttf|woff|woff2)$
    -   id: python-safety-dependencies-check
        name: Python Safety Check
        entry: safety
        args: [check, --full-report]
        language: system
        files: requirements
#    -   id: python-bandit-vulnerability-check
#        entry: bandit
#        name: Bandit Security Check
#        args: [-lll, --recursive, spedsa]
#        language: system
#        files: ''
    # -   id: tests
    #     name: run tests
    #     entry: pytest -v
    #     language: system
    #     types: [python]
    #     stages: [push]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'master'  # Use the sha / tag you want to point at
    hooks:
    - id: mypy
